baseurl = "https://steinn.org"
languageCode = "en-us"
title = "steinn.org"
theme = "lakkris"
pygmentsstyle = "monokai"

[params]
    gaCode = "UA-66867767-1"

[[menu.main]]
    name = "about"
    weight = -10
    identifier = "about"
    url = "/about/"
