baseurl = "http://steinn.org"
languageCode = "en-us"
title = "steinn.org"
theme = "lakkris"
pygmentsstyle = "monokai"

[[menu.main]]
    name = "about"
    weight = -10
    identifier = "about"
    url = "/about/"
